config/routes.rb
Subscribem::Engine.routes.draw do
    root "dashboard#index"

    get "/sign_up", :to => "accounts#new", :as => :sign_up
    post "/accounts", :to => "accounts#create", :as => :accounts
end

app/models/subscribem/account.rb
module Subscribem
  class Account < ApplicationRecord
    belongs_to :owner, :class_name => "Subscribem::User"
    accepts_nested_attributes_for :owner
  end
end

app/models/subscribem/application_record.rb
module Subscribem
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/subscribem/user.rb
module Subscribem
  class User < ApplicationRecord
    has_secure_password
  end
end

app/controllers/subscribem/accounts_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class AccountsController < ApplicationController
  
    def new
      @account = Subscribem::Account.new
      @account.build_owner
    end

    def create
      account = Subscribem::Account.create(account_params)
      flash[:success] = "Your account has been successfully created."
      redirect_to subscribem.root_url
    end

    private
      def account_params
        params.require(:account).permit(:name)
      end

  end
end

app/controllers/subscribem/application_controller.rb
module Subscribem
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/subscribem/dashboard_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class DashboardController < ApplicationController
  end
end

app/helpers/subscribem/accounts_helper.rb
module Subscribem
  module AccountsHelper
  end
end

app/helpers/subscribem/application_helper.rb
module Subscribem
  module ApplicationHelper
  end
end

app/helpers/subscribem/dashboard_helper.rb
module Subscribem
  module DashboardHelper
  end
end

app/views/layouts/subscribem/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Subscribem</title>
  <%= stylesheet_link_tag    "subscribem/application", media: "all" %>
  <%= javascript_include_tag "subscribem/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <% flash.each do |k,v| %>
   <div class='flash <%= k %>'><%= v %></div>
   <% end %>
<%= yield %>

</body>
</html>

app/views/subscribem/accounts/new.html.erb
<h2>Sign Up</h2>
<%= form_for(@account) do |account| %>
    <p>
        <%= account.label :name %><br>
        <%= account.text_field :name %>
    </p>
<%= account.fields_for :owner do |owner| %>
    <p>
      <%= owner.label :email %><br>
      <%= owner.email_field :email %>
    </p>
    <p>
      <%= owner.label :password %><br>
      <%= owner.password_field :password %>
    </p>
    <p>
      <%= owner.label :password_confirmation %><br>
      <%= owner.password_field :password_confirmation %>
    </p>

    <%= account.submit %>
<% end %>

app/views/subscribem/dashboard/index.html.erb
<%= link_to "Account Sign Up", sign_up_path %>